version: '3'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
    depends_on:
      - reservations_db

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
    depends_on:
      - auth_db

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
    depends_on:
      - payments_db

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
    depends_on:
      - notifications_db

  reservations_db:
    image: postgres
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_password
    networks:
      - app_network

  auth_db:
    image: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    networks:
      - app_network

  payments_db:
    image: postgres
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_password
    networks:
      - app_network

  notifications_db:
    image: postgres
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: notifications_password
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  app_network:
